services:
  my-server:
    build: .
    volumes:
      - movie-data:/app/data
    ports:
      - "80:5000"
    depends_on:
      my-db:
        condition: service_healthy
  my-db:
    image: mongo
    container_name: my-db
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd1234
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 10
      start_period: 3s

volumes:
  mongo-data:
  movie-data:
